# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Graduation_Project002' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Graduation_Project002
	pod 'Alamofire', '~> 5.0'
	pod 'SDWebImage', '~> 5.5.2'
	pod 'SDWebImageSwiftUI', '~> 0.10.3'
	pod 'SQLite.swift', '~> 0.12.0'
	
end

